name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Generate snake game
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: SahanB200
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#1e40af&color_dots=#0f172a,#1e293b,#334155,#475569,#64748b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
